/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat_peminjam = new javax.swing.JTextArea();
        status = new javax.swing.JTextField();
        print1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jenis = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 490, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Anggota");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Peminjam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat Peminjam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 160, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Buku");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 290, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Judul Buku");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 340, 110, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Pinjam");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 150, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Kembali");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 440, 150, 40);
        getContentPane().add(judul);
        judul.setBounds(140, 340, 170, 40);
        getContentPane().add(no);
        no.setBounds(140, 80, 170, 40);
        getContentPane().add(txtNama);
        txtNama.setBounds(140, 130, 170, 40);
        getContentPane().add(tgl_kembali);
        tgl_kembali.setBounds(140, 440, 170, 40);
        getContentPane().add(tgl_pinjam);
        tgl_pinjam.setBounds(140, 390, 170, 40);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(1).setResizable(false);
            tblData.getColumnModel().getColumn(2).setResizable(false);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(4).setResizable(false);
            tblData.getColumnModel().getColumn(5).setResizable(false);
            tblData.getColumnModel().getColumn(6).setResizable(false);
            tblData.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 130, 890, 402);

        alamat_peminjam.setColumns(20);
        alamat_peminjam.setRows(5);
        jScrollPane2.setViewportView(alamat_peminjam);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 190, 166, 96);
        getContentPane().add(status);
        status.setBounds(140, 490, 170, 40);

        print1.setText("print");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });
        getContentPane().add(print1);
        print1.setBounds(660, 80, 80, 40);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setForeground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(null);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("The Real Informatic School");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 40, 128, 14);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM Pengembalian Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 255, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1310, 60);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(760, 80, 90, 40);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setLayout(null);

        print.setText("refresh");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print);
        print.setBounds(540, 10, 110, 40);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(40, 10, 80, 40);

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(230, 10, 80, 40);

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(140, 10, 80, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 70, 980, 60);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(null);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pengetahuan", "Pemrograman", "KaryaIlmiah", "Novel", " " }));
        jPanel3.add(jenis);
        jenis.setBounds(140, 230, 160, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("JIKA TEPAT WAKTU ISI DENGAN 'CLEAR'");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 480, 330, 10);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("==================== JUJUR ITU BAIK! =====================");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 500, 330, 10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("*NB: JIKA ANDA MENGEMBALIKAN LEBIH DARI 3 HARI MAKA ISI DENGAN \"LATE\"   ");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 470, 330, 10);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 70, 320, 520);

        setSize(new java.awt.Dimension(1329, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:   
        
        
        String kondisi = status.getText();
        if("".equals(no.getText()) || "".equals(txtNama.getText()) || "".equals(jenis) ||"".equals(alamat_peminjam.getText()) || "".equals(judul.getText()) || "".equals(tgl_pinjam) || "".equals(tgl_kembali) || "".equals(status.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } 
        
        
        else if (kondisi == "LATE"){
            JOptionPane.showMessageDialog(this, "DENDA 3000", "DENDA", JOptionPane.WARNING_MESSAGE);
        }
            
        
 
        
        else
        {   
            
            String SQL = "INSERT INTO tb_peminjam (NoAnggota,Nama,Alamat,jenis,JudulBuku,TanggalPinjam,TanggalKembali,status)" + "VALUES('" + no.getText()+"','"+ txtNama.getText()+"','"+ alamat_peminjam.getText()+"','"+ jenis.getSelectedItem() +"','"+ judul.getText()+"','"+ tgl_pinjam.getDate() +"','"+ tgl_kembali.getDate() +"','"+ status.getText()+"')";
            int status = KoneksiDB.execute(SQL);
           
            
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        no.setText("");
        txtNama.setText("");
        alamat_peminjam.setText("");
        buttonGroup1.clearSelection();
        judul.setText("");
        tgl_pinjam.setCalendar(null);
        tgl_kembali.setCalendar(null);
        status.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_printActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
       if (baris != -1){
           String NoAnggota = tblData.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tb_peminjam WHERE NoAnggota='"+NoAnggota+"'";
           int status = KoneksiDB.execute(SQL);
           if(status==1){
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else{
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       } else{
           JOptionPane.showMessageDialog(this, "Pilih Baris Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_deleteActionPerformed

     private void tblDataMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris!=1){
            no.setText(tblData.getValueAt(baris, 0).toString());
            txtNama.setText(tblData.getValueAt(baris, 1).toString());
        
            alamat_peminjam.setText(tblData.getValueAt(baris, 3).toString());
            
            status.setText(tblData.getValueAt(baris, 4).toString());
            
            judul.setText(tblData.getValueAt(baris, 5).toString());
          
            
         
            
              
            
        }
    }     
    
    
    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Perpustakaan");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_print1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        if("".equals(no.getText()) || "".equals(txtNama.getText())|| "".equals(alamat_peminjam.getText())|| "".equals(status.getText())|| "".equals(tgl_pinjam) || "".equals(tgl_kembali)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else{

            String SQL = "UPDATE tb_peminjam SET "
            + "Nama='"+txtNama.getText()+"', "
            +"Jenis='"+ jenis +"', "
            + "Alamat='"+alamat_peminjam.getText()+"', "
            + "TanggalPinjam='"+tgl_pinjam+"', "
            + "TanggalKembali='"+tgl_kembali+"', "
            + "JudulBuku='"+status.getText()+"', "

            + "WHERE NoAnggota='"+no.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_peminjam;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField no;
    private javax.swing.JButton print;
    private javax.swing.JButton print1;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoAnggota","NamaPeminjam","AlamatPeminjam","JenisBuku","JudulBuku","tgl_pinjam","tgl_kembali","status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_peminjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NoAnggota = rs.getString(1);
                String NamaPeminjam = rs.getString(2);
                String AlamatPeminjam = rs.getString(3);
                String JenisBuku = rs.getString(4);
                String JudulBuku = rs.getString(5);
                String tgl_pinjam = rs.getString(6);
                String tgl_kembali = rs.getString(7);
                String status = rs.getString(8);
                String data[] = {NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,tgl_pinjam,tgl_kembali,status};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}

